"""Entry point for ``python -m optimalx_link`` and the ``optimalx-link``
console script.

Intentionally tiny: bootstrap the Qt app, construct the window and
controller, and hand off. All wiring lives in :mod:`app_controller`.
"""

from __future__ import annotations

import sys


def main(argv: list[str] | None = None) -> int:
    """Launch the GUI. Returns the Qt exit code so callers (and the
    ``console_scripts`` shim generated by setuptools) can `sys.exit` on it.

    Importing PySide6 happens here, not at module import time, so non-GUI
    consumers (e.g., tests, ad-hoc scripts that only use the server or
    archive APIs) don't pay the Qt startup cost.
    """
    from PySide6.QtWidgets import QApplication

    from .app_controller import AppController
    from .gui.main_window import MainWindow

    app = QApplication(argv or sys.argv)
    app.setApplicationName("OptimalX Link")
    app.setOrganizationName("OptimalX")

    window = MainWindow()
    controller = AppController(window, parent=app)
    # Make sure the controller's `stop()` runs before the QApplication tears
    # the event loop down — otherwise the async bridge thread can outlive
    # signals it's still trying to emit.
    app.aboutToQuit.connect(controller.stop)
    controller.start()

    window.show()
    return app.exec()


if __name__ == "__main__":
    sys.exit(main())
